### ISSUE TITLE
Not working / Loading

### ISSUE THREAD

**Issue by viviann16** [lovac42/KittenRewards#5]
This is the message I got whenever I opened Anki... not sure what it means or what I should do to fix it:

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Kitten Rewards Gamification⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/VivNguyen/Library/Application Support/Anki2/addons21/1627107763/__init__.py", line 1, in <module>
    from . import kittenRewards
  File "/Users/VivNguyen/Library/Application Support/Anki2/addons21/1627107763/kittenRewards.py", line 9, in <module>
    from aqt.mediasrv import RequestHandler
ImportError: cannot import name 'RequestHandler' from 'aqt.mediasrv' (/Applications/Anki.app/Contents/MacOS/aqt/mediasrv.pyc)
⁩

**Comment by lovac42** [comment]
There were many changes made to Anki in recent versions. This just means you are using a version that is not compatible and I hadn't had to time to update this addon properly yet that would match the changes made.

Each addon page has a specific Anki version listed:
![image](https://user-images.githubusercontent.com/42665127/103721318-5f294f00-4f9b-11eb-8991-282869094a3a.png)

In the mean time, you may use this patch made by another user: https://github.com/dannyreilman/KittenRewards/blob/master/src21/kittenRewards.py. (Copy and paste) There are security reasons why I don't use this and opt to rewrite it instead.

Hope this helped clarify the current addon situation.

**Comment by felipemldias** [comment]
I'm afraid this solution no longer works on 2.1.42
